<section id="main" class="pm-my-tasks ca-management" data-pm-my-tasks data-scroll-key="pm-my-tasks-filters">
    <header class="pm-my-tasks-header"><span><?= t('CompanyAgile: Operational dashboard') ?></span><h1><?= t('CompanyAgile: My tasks') ?></h1><p><?= t('CompanyAgile: Assigned work overview for %s', $represented_user_name) ?></p></header>

    <div class="pm-my-tasks-toolbar">
        <?php if ($can_inspect_users): ?><?= $this->render('companyAgile:management/picker', array('name' => 'user_id', 'label' => t('CompanyAgile: User'), 'items' => $users, 'value' => $represented_user['id'], 'search_label' => t('CompanyAgile: Search or select user...'), 'placeholder' => t('CompanyAgile: Search or select user...'), 'clear_label' => '', 'remote_url' => $user_search_url)) ?><?php endif ?>
        <label class="pm-my-tasks-search"><span><?= t('CompanyAgile: Search tasks') ?></span><input type="search" value="<?= $this->text->e($search) ?>" placeholder="<?= t('CompanyAgile: Search by ID or title...') ?>" data-pm-task-search></label>
        <div class="pm-priority-filter"><span><?= t('CompanyAgile: Priority') ?></span><div><?php foreach (array('high' => t('CompanyAgile: High'), 'normal' => t('CompanyAgile: Normal'), 'low' => t('CompanyAgile: Low')) as $value => $label): ?><button type="button" data-pm-priority="<?= $value ?>" aria-pressed="<?= $priority === $value ? 'true' : 'false' ?>"><?= $label ?></button><?php endforeach ?></div></div>
        <form class="ca-management-filter-form" method="get" action="<?= $this->url->href('MyTasksController', 'show', array('plugin' => 'CompanyAgile')) ?>" data-pm-task-filter-form>
            <input type="hidden" name="user_id" value="<?= (int) $represented_user['id'] ?>" data-pm-filter="user_id" data-ca-management-filter="user_id"><input type="hidden" name="project_ids" value="<?= $this->text->e(implode(',', $selected_project_ids)) ?>" data-pm-filter="project_ids" data-ca-management-filter="project_ids"><input type="hidden" name="column_ids" value="<?= $this->text->e(implode(',', $selected_column_ids)) ?>" data-pm-filter="column_ids" data-ca-management-filter="column_ids"><input type="hidden" name="priority" value="<?= $this->text->e($priority) ?>" data-pm-filter="priority"><input type="hidden" name="search" value="<?= $this->text->e($search) ?>" data-pm-filter="search">
        </form>
    </div>

    <div class="pm-task-metrics"><article><strong><?= $summary['task_count'] ?></strong><span><?= t('CompanyAgile: Open tasks') ?></span></article><article><strong><?= $summary['project_count'] ?></strong><span><?= t('CompanyAgile: Projects involved') ?></span></article><article><strong><?= $summary['high_count'] ?></strong><span><?= t('CompanyAgile: High priority') ?></span></article><article><strong><?= $summary['overdue_count'] ?></strong><span><?= t('CompanyAgile: Overdue') ?></span></article></div>

    <div class="pm-task-facets">
        <section><h2><?= t('CompanyAgile: By project') ?></h2><div><?php foreach ($summary['projects'] as $project): ?><button type="button" class="pm-facet<?= in_array((int) $project['id'], $selected_project_ids, true) ? ' is-active' : '' ?>" data-pm-filter-group="project_ids" data-pm-filter-values="<?= (int) $project['id'] ?>" aria-pressed="<?= in_array((int) $project['id'], $selected_project_ids, true) ? 'true' : 'false' ?>"><strong><?= (int) $project['task_count'] ?></strong><?= $this->text->e($project['name']) ?></button><?php endforeach ?></div></section>
        <section><h2><?= t('CompanyAgile: Current workflow') ?></h2><div><?php foreach ($summary['columns'] as $column): ?><?php $active = (bool) array_intersect($column['ids'], $selected_column_ids) ?><button type="button" class="pm-facet<?= $active ? ' is-active' : '' ?>" data-pm-filter-group="column_ids" data-pm-filter-values="<?= $this->text->e(implode(',', $column['ids'])) ?>" aria-pressed="<?= $active ? 'true' : 'false' ?>"><strong><?= (int) $column['task_count'] ?></strong><?= $this->text->e($column['title']) ?></button><?php endforeach ?></div></section>
        <?php if (! empty($selected_project_ids) || ! empty($selected_column_ids) || $priority !== '' || $search !== ''): ?><button type="button" class="pm-clear-filters" data-pm-clear-task-filters><?= t('CompanyAgile: Clear filters') ?></button><?php endif ?>
    </div>

    <?php if (! empty($attention)): ?><section class="pm-attention"><header><div><h2><?= t('CompanyAgile: Needs attention') ?></h2><p><?= t('CompanyAgile: Tasks requiring priority or deadline attention') ?></p></div></header><div><?php foreach ($attention as $task): ?><?php $attentionState = $task['date_due'] > 0 && $task['date_due'] < time() ? 'overdue' : ($task['priority'] > 0 ? 'high' : 'due') ?><a href="<?= $this->url->href('TaskViewController', 'show', array('task_id' => $task['id'])) ?>" class="pm-attention-card pm-attention-<?= $attentionState ?> ca-task-link" data-task-id="<?= (int) $task['id'] ?>"><span><?= $attentionState === 'overdue' ? t('CompanyAgile: Overdue') : ($attentionState === 'high' ? t('CompanyAgile: High') : t('CompanyAgile: Due soon')) ?></span><strong><b>#<?= (int) $task['id'] ?></b><?= $this->text->e($task['title']) ?></strong><small><?= $this->text->e($task['project_name']) ?> · <?= $this->text->e($task['column_name']) ?><?php if ((int) $task['date_due'] > 0): ?> · <?= $this->dt->date($task['date_due']) ?><?php endif ?></small></a><?php endforeach ?></div></section><?php endif ?>

    <section class="pm-assigned-work" id="pm-assigned-work"><header><div><h2><?= t('CompanyAgile: All assigned tasks') ?></h2><p><?= t('CompanyAgile: Tasks grouped by project and workflow') ?></p></div><span><?= $paginator->getTotal() ?> <?= t('CompanyAgile: tasks') ?></span></header>
        <?php if (empty($tasks)): ?><p class="ca-management-empty"><?= t('There is nothing assigned to you.') ?></p><?php else: ?>
            <?php foreach ($task_groups as $group): ?><details class="pm-project-group" open><summary><strong><?= $this->text->e($group['name']) ?></strong><span><?= (int) $group['count'] ?></span></summary><div>
                <?php foreach ($group['columns'] as $columnName => $columnTasks): ?><section class="pm-column-group"><header><h3><?= $this->text->e($columnName) ?></h3><span><?= count($columnTasks) ?></span></header><div><?php foreach ($columnTasks as $task): ?>
                    <a class="pm-task-card ca-task-link" data-task-id="<?= (int) $task['id'] ?>" href="<?= $this->url->href('TaskViewController', 'show', array('task_id' => $task['id'])) ?>"><span>#<?= (int) $task['id'] ?></span><strong><?= $this->text->e($task['title']) ?></strong><small><?= $task['priority'] > 0 ? t('CompanyAgile: High') : ($task['priority'] < 0 ? t('CompanyAgile: Low') : t('CompanyAgile: Normal')) ?><?php if ($task['story_points'] !== null): ?> · <?= $this->text->e($task['story_points']) ?> SP<?php endif ?><?php if ((int) $task['date_due'] > 0): ?> · <?= $this->dt->date($task['date_due']) ?><?php endif ?></small></a>
                <?php endforeach ?></div></section><?php endforeach ?></div></details><?php endforeach ?>
            <?= $paginator ?>
        <?php endif ?>
    </section>
</section>
