<div class="ca-filter-bar" data-ca-filter-bar data-ca-no-results-prefix="<?= t('CompanyAgile: No results for') ?>" data-ca-active-label="<?= t('CompanyAgile: Active filters') ?>" data-ca-advanced-label="<?= t('CompanyAgile: Advanced query') ?>" data-ca-apply-label="<?= t('CompanyAgile: Apply') ?>" data-ca-clear-label="<?= t('CompanyAgile: Clear filters') ?>">
    <div class="ca-filter-heading"><span><?= t('CompanyAgile: Filter board') ?></span><small><?= t('CompanyAgile: Quick filters') ?></small></div>
    <div class="ca-filter-actions">
        <div class="ca-filter-menu" data-ca-popover>
            <button type="button" class="ca-filter-chip" data-ca-popover-trigger aria-expanded="false"><i class="fa fa-user"></i> <span data-ca-trigger-label><?= t('CompanyAgile: Assignee') ?></span> <i class="fa fa-angle-down"></i></button>
            <div class="ca-filter-popover" data-ca-popover-panel hidden><label class="ca-popover-search"><i class="fa fa-search"></i><input type="search" placeholder="<?= t('CompanyAgile: Search assignee...') ?>" data-ca-option-search></label><div class="ca-popover-options" role="listbox"><?php foreach ($users as $userId => $userName): ?><button type="button" role="option" data-ca-option data-ca-filter="assignee:&quot;<?= $this->text->e($userName) ?>&quot;"><?= $this->text->e($userName) ?></button><?php endforeach ?><p class="ca-popover-empty" data-ca-empty-state><?= t('CompanyAgile: No users found.') ?></p><p class="ca-popover-no-results" data-ca-no-results hidden></p></div></div>
        </div>
        <div class="ca-filter-menu" data-ca-popover>
            <button type="button" class="ca-filter-chip" data-ca-popover-trigger aria-expanded="false"><i class="fa fa-check-square-o"></i> <span data-ca-trigger-label><?= t('CompanyAgile: Issue type') ?></span> <i class="fa fa-angle-down"></i></button>
            <div class="ca-filter-popover" data-ca-popover-panel hidden><div class="ca-popover-options" role="listbox"><?php foreach ($issue_types as $type): ?><button type="button" role="option" data-ca-option data-ca-type-filter="<?= $this->text->e($type['code']) ?>"><?= t('CompanyAgile issue type: '.$type['code']) ?></button><?php endforeach ?></div></div>
        </div>
        <div class="ca-filter-menu" data-ca-popover>
            <button type="button" class="ca-filter-chip" data-ca-popover-trigger aria-expanded="false"><i class="fa fa-diamond"></i> <span data-ca-trigger-label><?= t('CompanyAgile: Epic') ?></span> <i class="fa fa-angle-down"></i></button>
            <div class="ca-filter-popover" data-ca-popover-panel hidden><label class="ca-popover-search"><i class="fa fa-search"></i><input type="search" placeholder="<?= t('CompanyAgile: Search Epic...') ?>" data-ca-option-search></label><div class="ca-popover-options" role="listbox"><button type="button" role="option" data-ca-option data-ca-epic-filter="all"><?= t('CompanyAgile: All') ?></button><button type="button" role="option" data-ca-option data-ca-epic-filter="none"><?= t('CompanyAgile: No Epic') ?></button><?php foreach ($epics as $epic): ?><button type="button" role="option" data-ca-option data-ca-epic-filter="<?= (int) $epic['id'] ?>">#<?= (int) $epic['id'] ?> <?= $this->text->e($epic['title']) ?></button><?php endforeach ?><p class="ca-popover-no-results" data-ca-no-results hidden></p></div><?php if (empty($epics)): ?><p class="ca-popover-empty ca-is-visible"><?= t('CompanyAgile: No Epics registered.') ?></p><?php endif ?><?php if ($can_create_tasks): ?><button type="button" class="ca-popover-create" data-ca-create-epic><i class="fa fa-plus"></i> <?= t('CompanyAgile: Create Epic') ?></button><?php endif ?></div>
        </div>
        <div class="ca-filter-menu" data-ca-popover>
            <button type="button" class="ca-filter-chip" data-ca-popover-trigger aria-expanded="false"><i class="fa fa-calendar"></i> <span data-ca-trigger-label><?= t('CompanyAgile: Sprint') ?></span> <i class="fa fa-angle-down"></i></button>
            <div class="ca-filter-popover" data-ca-popover-panel hidden><label class="ca-popover-search"><i class="fa fa-search"></i><input type="search" placeholder="<?= t('CompanyAgile: Search Sprint...') ?>" data-ca-option-search></label><div class="ca-popover-options" role="listbox"><button type="button" role="option" data-ca-option data-ca-sprint-filter="all"><?= t('CompanyAgile: All') ?></button><button type="button" role="option" data-ca-option data-ca-sprint-filter="active"><?= t('CompanyAgile: Active Sprint') ?></button><button type="button" role="option" data-ca-option data-ca-sprint-filter="backlog"><?= t('CompanyAgile: Backlog') ?></button><?php foreach ($sprints as $sprint): ?><button type="button" role="option" data-ca-option data-ca-sprint-filter="<?= (int) $sprint['id'] ?>"><?= $this->text->e($sprint['name']) ?></button><?php endforeach ?><p class="ca-popover-no-results" data-ca-no-results hidden></p></div><?php if (empty($sprints)): ?><p class="ca-popover-empty ca-is-visible"><?= t('CompanyAgile: No Sprints yet') ?></p><?php endif ?><?php if ($can_manage_project): ?><a class="ca-popover-create js-modal-medium" href="<?= $this->url->href('SprintController', 'create', array('plugin' => 'CompanyAgile', 'project_id' => $project['id'])) ?>"><i class="fa fa-plus"></i> <?= t('CompanyAgile: Create Sprint') ?></a><?php endif ?></div>
        </div>
        <div class="ca-filter-menu" data-ca-popover><button type="button" class="ca-filter-chip" data-ca-popover-trigger aria-expanded="false"><i class="fa fa-arrow-up"></i> <span data-ca-trigger-label><?= t('CompanyAgile: Priority') ?></span> <i class="fa fa-angle-down"></i></button><div class="ca-filter-popover" data-ca-popover-panel hidden><div class="ca-popover-options" role="listbox"><button type="button" role="option" data-ca-option data-ca-filter="priority:&gt;0"><?= t('CompanyAgile: High') ?></button><button type="button" role="option" data-ca-option data-ca-filter="priority:0"><?= t('CompanyAgile: Normal') ?></button><button type="button" role="option" data-ca-option data-ca-filter="priority:&lt;0"><?= t('CompanyAgile: Low') ?></button></div></div></div>
        <div class="ca-filter-menu" data-ca-popover><button type="button" class="ca-filter-chip" data-ca-popover-trigger aria-expanded="false"><i class="fa fa-circle-o"></i> <span data-ca-trigger-label><?= t('CompanyAgile: Status') ?></span> <i class="fa fa-angle-down"></i></button><div class="ca-filter-popover" data-ca-popover-panel hidden><div class="ca-popover-options" role="listbox"><button type="button" role="option" data-ca-option data-ca-filter="status:open"><?= t('CompanyAgile: Open') ?></button><button type="button" role="option" data-ca-option data-ca-filter="status:closed"><?= t('CompanyAgile: Closed') ?></button></div></div></div>
        <div class="ca-filter-menu" data-ca-popover>
            <button type="button" class="ca-filter-chip" data-ca-popover-trigger aria-expanded="false"><i class="fa fa-tag"></i> <span data-ca-trigger-label><?= t('CompanyAgile: Tags') ?></span> <i class="fa fa-angle-down"></i></button>
            <div class="ca-filter-popover" data-ca-popover-panel data-ca-multi-popover="tag" hidden><label class="ca-popover-search"><i class="fa fa-search"></i><input type="search" placeholder="<?= t('CompanyAgile: Search tag...') ?>" data-ca-option-search></label><div class="ca-popover-options" role="listbox" aria-multiselectable="true"><?php foreach ($tags as $tag): ?><button type="button" role="option" class="<?= (int) $tag['project_id'] > 0 ? 'ca-tag-project' : 'ca-tag-global' ?>" data-ca-option data-ca-multi-value="<?= $this->text->e($tag['name']) ?>" aria-selected="false"><i class="fa fa-square-o" aria-hidden="true"></i> <?= $this->text->e($tag['name']) ?></button><?php endforeach ?><p class="ca-popover-empty" data-ca-empty-state><?= t('CompanyAgile: No tags registered.') ?></p><p class="ca-popover-no-results" data-ca-no-results hidden></p></div><button type="button" class="ca-popover-apply" data-ca-apply-multi><?= t('CompanyAgile: Apply') ?></button><?php if ($can_manage_project): ?><form class="ca-popover-create-form" action="<?= $this->url->href('FilterController', 'createTag', array('plugin' => 'CompanyAgile', 'project_id' => $project['id'])) ?>" method="post"><?= $this->form->csrf() ?><input type="text" name="name" placeholder="<?= t('CompanyAgile: Type a tag...') ?>" required maxlength="255"><button type="submit" class="ca-popover-create"><i class="fa fa-plus"></i> <?= t('CompanyAgile: Create tag') ?></button><small role="status"></small></form><?php endif ?></div>
        </div>
        <button type="button" class="ca-filter-more" data-ca-advanced-toggle><i class="fa fa-sliders"></i> <?= t('CompanyAgile: Advanced search') ?></button><button type="button" class="ca-filter-clear" data-ca-filter-clear title="<?= t('CompanyAgile: Clear filters') ?>"><i class="fa fa-times"></i></button>
    </div>
</div>
